### ISSUE TITLE
More OS integration

### ISSUE THREAD

**Issue by z-------------** [z-------------/CPod#103]
* ~~Integration with keyboard media keys for playback control with program in background~~ (9685c105666f512b3e586967bb510d354602f71e)
* ~~Minimize to taskbar~~ (39d23a30ca217d9e4bb704773e0b9cf610c46d67)
* ~~Close podcast detail view with Esc key~~ (7e46fe90f816cff3c576441ec74f1e409632b1d5)

(#98)

cf. #34, #90

**Comment by z-------------** [comment]
@ZeroDot1 Will do.

**Comment by EmperorEarth** [comment]
Does this [help](https://github.com/twolfson/google-music-electron/blob/1.19.0/lib/shortcuts.js)?

**Comment by z-------------** [comment]
@EmperorEarth Yes that helps a lot, not sure how I didn't know of that API. Thanks.

**Comment by EmperorEarth** [comment]
* [Some official docs](https://github.com/electron/electron/blob/master/docs/api/tray.md)
* [Issue thread on minimize to tray for different app](https://github.com/signalapp/Signal-Desktop/issues/1480)
* [Commit of a discontinued open source repo with an implementation](https://github.com/Enrico204/Whatsapp-Desktop/tree/e246043625d4db26ce705cf10894a6ff3336474b)

Sorry, not as direct this time, bit busy coding!
