### ISSUE TITLE
Cpod not working in Kubuntu 18.10

### ISSUE THREAD

**Issue by barkingbandicoot** [z-------------/CPod#106]
**CPod version:** 25 & 26 versions

**Platform:**
Kubuntu Cosmic Cuttlefish
**Description:**
.debs will not launch or install. Snap crashes upon searching for podcast
**Did the bug only start to occur after a CPod update? Version before, version after:**
Bug started after update from Kubuntu 18.04 to 18.10

**Steps to reproduce:**

**Please also attach information that might help, e.g. screenshots of Developer Tools console log, if possible.**

**Comment by barkingbandicoot** [comment]
Cumulonimbus 1.9.6 however does work!

**Comment by usernamefoo** [comment]
Seems that alot of electron apps are broken on 18.10.
https://github.com/Foundry376/Mailspring/issues/1108

**Comment by barkingbandicoot** [comment]
> Seems that alot of electron apps are broken on 18.10.
> [Foundry376/Mailspring#1108](https://github.com/Foundry376/Mailspring/issues/1108)

Ah, ok. Yes, I had problems with Mailsping also. Cpod is an electon app too then!
Should the bug reports be directed at Kubuntu then - or will app creators eventually (fingers crossed) bring out compatible versions???

**Comment by z-------------** [comment]
Thanks for letting me know about this.

I've had a few people open issues (#92, #93) about various crashes that had prompted me to downgrade from Electron 2.0.8 to 2.0.0, but those might actually be an issue with the unofficial Snap releases of CPod instead — I had never been able to reproduce them.

[Here's](https://github.com/z-------------/CPod/releases/tag/v1.27.0) a new build under Electron 2.0.12 (the latest stable 2.x.x). Please let me know if there are any problems.

**Comment by barkingbandicoot** [comment]
> Thanks for letting me know about this.
> 
> I've had a few people open issues (#92, #93) about various crashes that had prompted me to downgrade from Electron 2.0.8 to 2.0.0, but those might actually be an issue with the unofficial Snap releases of CPod instead — I had never been able to reproduce them.
> 
> [Here's](https://github.com/z-------------/CPod/releases/tag/v1.27.0) a new build under Electron 2.0.12 (the latest stable 2.x.x). Please let me know if there are any problems.

Oh, fantastic! It works great and picked up all my previous subscriptions!
Thank you!
