### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Jackymancs4** [z-------------/CPod#111]
**CPod version:**
1.27

**Platform:**
MacOS 10.13.1

**Install type (.deb, Snap, etc.):**
dmg

**Description:**

Hello @z------------- 
While working on #110 I encountered this error in the console.
Sorry but I really don't have time to investigate more.

**Did the bug only appear after a CPod update? Version before, after:**
From at least 1.26

**Steps to reproduce:**
- Open CPod
- Open Developer Tools with ```cmd+shift+i```
- Look in the console

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:*

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at calculateCanvasDimens (cbus-ui.js:1139)
    at cbus-ui.js:663
calculateCanvasDimens @ cbus-ui.js:1139
(anonymous) @ cbus-ui.js:663
requestAnimationFrame (async)
func @ cbus-ui.js:662
```
<img width="686" alt="schermata 2018-10-27 alle 17 55 08" src="https://user-images.githubusercontent.com/6209647/47606245-7bbbbb00-da11-11e8-9f78-c3492f53e133.png">

**Comment by z-------------** [comment]
Thanks for pointing this out. I've been aware of this error for a while but have never gotten around to doing anything about it. It doesn't affect CPod's functionality.
