### ISSUE TITLE
All releases are pre-releases

### ISSUE THREAD

**Issue by Jackymancs4** [z-------------/CPod#112]
In https://github.com/z-------------/CPod/releases, every release is a pre-release.

So I was wondering if it was intended or not.
Right now (on MacOs architecture) CPod will not update at all if the setting ```Allow pre-releases when auto-updating``` is left uncheck (default), which is quite unintuitive.

**Comment by z-------------** [comment]
This is intentional. I want to allow more time for any bug reports related to newer features, as well as for translations to become more or less complete, before I release new "stable" builds.
