### ISSUE TITLE
issue in darkmode theme

### ISSUE THREAD

**Issue by Monirzadeh** [z-------------/CPod#116]
CPod v1.27.0
kubuntu 18.04
appimage
**Description:**
the text is light same as background in dark mode so you can't see the text of unselected option in a drop-down menu
**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:*
![bug cpod in dark mode](https://cdn.pbrd.co/images/HMReDGW.png)

**Comment by z-------------** [comment]
Thanks for submitting this issue. This bug has already been addressed in #109 and the fix will be included in the next release of CPod.
