### ISSUE TITLE
Crashes when clicking in Explore, Search field

### ISSUE THREAD

**Issue by colbobs** [z-------------/CPod#124]
**CPod version:** v1.25.7

**Platform:** Linux Ubuntu 17.10 Gnome

**Install type (.deb, Snap, etc.):** snap

**Description:** crashes on clicking in search field via explore icon, every time.

**Did the bug only appear after a CPod update? Version before, after:** after. No new updates since

**Steps to reproduce:** launch, explore, click in search

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:*

**Comment by dixonge** [comment]
Same CPod version, same result

Lubuntu 18.10

**Comment by dixonge** [comment]
For comparison - just installed the 1.27 AppImage and it appears to be working just as expected, no crashes so far.

**Comment by z-------------** [comment]
Thank you both for the bug reports. This bug was introduced at some point seemingly by a clash between a particular update to Electron (the framework on which CPod is built) and certain dependencies on Linux. An update (v1.27.0) was released that fixes this, so please consider installing that version as dixonge has.

As for why the update did not appear in CPod's auto-updater, this could be a separate bug (assuming pre-releases are enabled in settings).

**Comment by colbobs** [comment]
Thank you, installed new AppImage and appears to be working great
For other users that might read this, I followed the guidelines for installing AppImages posted at https://itsfoss.com/use-appimage-linux/.

Super easy by the way.

This isn't a criticism of you at all Zack, but I find github pages to be somewhat lacking in obvious "how to".

For the benefit other newbie users I followed this route (please feel free to post this somewhere that might make it more useful):
Click on "code" in tab section next to "issues" which takes you to https://github.com/z-------------/CPod
Scroll down to "Install" and click on hyperlinked text "Get the latest releases." this takes us to https://github.com/z-------------/CPod/releases
My chosen file happens to be CPod-1.27.0-x86_64.AppImage.

Thanks for the update Zack.

**Comment by z-------------** [comment]
@colbobs, thanks. I've added some more detailed installation instructions in the new [Wiki](https://github.com/z-------------/CPod/wiki/Installation); hopefully people in future will find it useful.

**Comment by colbobs** [comment]
Thanks for the feedback on my feedback!
Have a good day there.
