### ISSUE TITLE
Unsubscribing doesn't affect home screen?

### ISSUE THREAD

**Issue by Baemir** [z-------------/CPod#126]
**CPod version:**
v1.27.0

**Platform:**
Windows 10

**Install type (.deb, Snap, etc.):**
.exe installer

**Description:**
Unsubscribing doesn't seem to remove any items from my home screen. All the episodes of the podcast I unsubbed from remain there. I'm assuming this is not the intended behavior?

**Comment by z-------------** [comment]
This is the intended behaviour, though I will work on implementing said functionality. Thanks.

**Comment by zrnsm** [comment]
I was confused by this same issue running on the 1.2.7 release and was about to open a ticket. Nice to see that it's been resolved. Looking forward to seeing this in a release.
