### ISSUE TITLE
Default podcasts?

### ISSUE THREAD

**Issue by tiotrom** [z-------------/CPod#129]
I see there are a bunch of podcasts in the search section that do not change and I was wondering where are those coming from?
![2019-01-16_13-04](https://user-images.githubusercontent.com/34804533/51248262-dd941d00-198f-11e9-9772-02c9d43119ee.png)

**Comment by z-------------** [comment]
These are coming from iTunes' top podcasts list, in your case the US version (set by the dropdown menu to the right of "Explore"). They change over time depending what is trending on iTunes.

**Comment by tiotrom** [comment]
I understand, thank you! Maybe in the future you can integrate other options for the suggestions, like based on the podcasts one is subscribed to. In any case, all looks and works great! :)

**Comment by z-------------** [comment]
Thank you for the suggestion, in fact that is one of the things I plan to work towards at some point.
