### ISSUE TITLE
Suggestion for changing the main icons ;) 

### ISSUE THREAD

**Issue by tiotrom** [z-------------/CPod#130]
I find the icons confusing :D - I am doing webdesign for many years now and based on my experience you need something more easily identifiable. Like a quick example I did
![2019-01-20_23-53](https://user-images.githubusercontent.com/34804533/51446336-03634e00-1d11-11e9-9295-1d3e79981dd1.png)

I know this is kinda subjective but I am always confused by the main icons. Cheers!

**Comment by z-------------** [comment]
Hi tiotrom, thank you for the suggestion. I think I want to keep the Home icon as-is, but I've mostly followed your suggestions elsewhere (84a3e33):

![Screenshot of updated nav icons](https://i.imgur.com/vWg19w9.png)

**Comment by tiotrom** [comment]
Awesome! Looks great! Very happy that you implemented the changes I suggested :)
