### ISSUE TITLE
Are you still working on this

### ISSUE THREAD

**Issue by KungFung** [z-------------/CPod#134]

**Comment by KungFung** [comment]
I am willing to bug test any new release

**Comment by z-------------** [comment]
Yes, I am still working on CPod. I've had a few things on my plate lately and I don't always want to work on CPod in my spare time, which is why progress has been slow.

**Comment by KungFung** [comment]
Okay, thanks for replying so quickly it's just that I love CPod and its something that I now use daily it's just an amazing tool to use.

**Comment by z-------------** [comment]
That's good to hear :) I'll be sure to keep improving CPod in the future.
