### ISSUE TITLE
Does not recognize podcast URL for services it does not know about.

### ISSUE THREAD

**Issue by jelabarre59** [z-------------/CPod#141]
**CPod version:**

**Platform:**

**Install type (.deb, Snap, etc.):**

**Description:**

**Did the bug only appear after a CPod update? Version before, after:**

**Steps to reproduce:**

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:**

**Comment by jelabarre59** [comment]
The "Explore" page has the entry box where you are supposed to be able to enter an RSS URL for a podcast.  But apparently, even though it is supposed to take a URL, it appears to only do a search against the text of the URL, and fails to find anything.

As an example: www.japanesepod101.com/feed.xml

CPod 1.27.1, Linux Mint 19.1

**Comment by z-------------** [comment]
Hi, have you tried entering the full URL, including the `http(s)://`?

**Comment by jelabarre59** [comment]
I'd have to re-install the appimage

**Comment by z-------------** [comment]
I just tried it myself, works with `http://www.japanesepod101.com/feed.xml`.
