### ISSUE TITLE
Option for "Show" the interface again when minimized/closed to taskbar

### ISSUE THREAD

**Issue by brunofunnie** [z-------------/CPod#144]
**CPod version:**
CPod v1.27.1

**Description:**
When closing/minimizing for taskbar (when the options are set in the configuration) it works fine, but, if you want to show the interface again it is not possible and if you open the cpod again it creates another thread/process. A good idead would be to have a "Show" option in the list.

![image](https://user-images.githubusercontent.com/5279392/58031318-88f7de80-7af6-11e9-8170-00a78dfbc0f1.png)

**Comment by z-------------** [comment]
Clicking the tray icon actually re-shows the CPod window on Windows, so this must be a Linux/Gnome thing, which I haven't tested on. I'll add the list option as suggested. Thanks.

**Comment by brunofunnie** [comment]
Gnome removed the appindicators from the core and now it's a extension. In any case the default click behavior is to open the menu, so there's no default click/double-click action. I don't know if it's possible to create a conditional to when it detects gnome it shows the "Show" item...

> Clicking the tray icon actually re-shows the CPod window on Windows, so this must be a Linux/Gnome thing, which I haven't tested it on. I'll add the list option as suggested. Thanks.

**Comment by z-------------** [comment]
06f252972c476f0738f3eb314c4a35e2e3846012 adds a "Show" option when Linux is detected:

![Screenshot](https://i.imgur.com/SnoUdZp.png)
