### ISSUE TITLE
Buy me a coffee link opens the link inside the app instead of a new browser tab

### ISSUE THREAD

**Issue by eralpsahin** [z-------------/CPod#146]
**CPod version:** v1.27.0 - v1.27.1

**Platform:** On Mac and Windows

**Install type (.deb, Snap, etc.):** .exe on Windows, .app and development install on mac

**Description:** On settings tab, links such as _View Licenses_, _Report an Issue_ etc. under `<div class="settings_section settings_about"` are handled by a click listener added to the parent `section` with the `settings` id in the file cbus-ui.js. Clicks inside this section are propagated and handled here.

Listener opens links in a new tab after this check;
`if (e.target.tagName === "A" && e.target.hasAttribute("href"))`

But, since _Buy me a coffee_ link has an image, the` e.target `becomes the `img` instead of the `<a>`and the listener will not handle this click in the expected way. Event does not take the above branch. It opens the link inside the app and there is no way to return back.

I am not sure if this is a bug but it seems it cannot be the expected thing.

**Steps to reproduce:** Under **Settings** scroll down and click on _Buy me a coffee_ image link. The link will open inside the app instead of a new browser tab and there is no way to go back.

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:**

```javascript
document.getElementById("settings").addEventListener("click", e => {
  if (e.target.tagName === "A" && e.target.hasAttribute("href")) {
    e.preventDefault();
    const href = e.target.getAttribute("href");
    const link = isUrl(href) ? href : fileUrl(href);
    remote.shell.openExternal(link);
  }
});
```
This can be fixed by either handling the buy me a coffee link on its own, or accepting tagNames to be `IMG` as well in the above if statement and relocating the href attribute of `settings_buy-me-a-coffee-link` to the `<img>` tag in `index.pug`. This way the `e.target` would still be the `img` but the listener would work as expected. I can make a pull request with the second solution but I am not sure how nice it is.

**Comment by z-------------** [comment]
Hello, this is indeed not the intended behavior. Thank you for the detailed bug report.

3cbb37cc020e4d362e2c616390a5c988f1e4e724 this, using your first suggestion.
