### ISSUE TITLE
Sound Volume Adjustment

### ISSUE THREAD

**Issue by ylivan09** [z-------------/CPod#147]
**CPod version:** 1.27.1

**Description:**
since there's no sound volume control, I have to adjust system sound vol every time when listen to podcast, please consider adding sound volume control.

it would be cool if I can sort multi subscription by category, would you please considering add this feature?
thank you.

**Comment by z-------------** [comment]
Hello, 

Regarding volume control, I will work on that.

Regarding subscription categories, are you suggesting something similar to #100?

**Comment by ylivan09** [comment]
I am not sure, I would give an example, say, when I subscribe to several podcasts from different channel like  BBC 3, BBC 4, I hope I can categorize it with The name BBC, maybe it's collection?

**Comment by z-------------** [comment]
Yes, that is covered by #100.

**Comment by z-------------** [comment]
Volume control has been added in PR #148 and will available in the next release. Progress on podcast categorizations will be in #100.
