### ISSUE TITLE
Bug with the UI of macOS menu bar

### ISSUE THREAD

**Issue by paulaime** [z-------------/CPod#151]
Hello!

**CPod version:** CPod v1.27.1

**Platform:** macOS 10.14.5

**Install type (.deb, Snap, etc.):** CPod-1.27.1-mac.zip downloaded from this GitHub repo

**Description:** When launching CPod, there's a yellow glitch with the macOS menu bar (see screenshot). I've tried to relaunch, to force reload, with the light skin and the dark skin and the problem persists.

**Did the bug only appear after a CPod update? Version before, after:** I was using CPod in the past (didn't have this bug), but then used another software for some time, and I just reinstalled CPod today and noticed this bug.

**Steps to reproduce:** Launch CPod on macOS and the bug appeared right away on the menu bar.

![Capture d’écran 2019-06-04 à 20 50 09](https://user-images.githubusercontent.com/51381451/58905897-1ba99780-870b-11e9-8445-1ef545b32ad1.jpg)

**Comment by eralpsahin** [comment]
I had this issue as well, thought the menu was actually another applications and it was just not playing well with CPod.

 It seems that "yellow glitch" is actually the icon but, zoomed. Those 3 gray bits are the three circles from the icon. I made a pull request fixing this #152.

<img width="500" alt="Screen Shot 2019-06-04 at 16 08 22" src="https://user-images.githubusercontent.com/10602289/58910244-0882d180-86e3-11e9-882a-e82596eb6ba1.png">

**Comment by paulaime** [comment]
Alright, that makes sense, thanks for the answer.
