### ISSUE TITLE
Support multiple enclosures

### ISSUE THREAD

**Issue by Hedath** [z-------------/CPod#159]
I 've found a podcast which is not working with CPod:
https://24.hu/feed/ziccer_24hu/
The issue is that each item in the rss has two enclosue tags (one image, and one audio). CPod seems to download the first one, so the audio is ignored. It would be cool if the audio enclosue could be downloaded.

**Comment by z-------------** [comment]
Thanks for the issue and specifically pointing out the problematic RSS feed, that really helped. This should be fixed in 10afe8d1bb53d3d185a92c5cce1dee1b7c6c7b1f.
