### ISSUE TITLE
show remaining time

### ISSUE THREAD

**Issue by ebal** [z-------------/CPod#164]
**CPod version:**
CPod v1.27.1

**Description:**

It would be great when clicking the total podcast time, 
if it can switched to show remaining time,
so you can see how much time you have listening on this podcast.

![image](https://user-images.githubusercontent.com/3049624/64062805-487b2700-cbf4-11e9-90cb-126964717cf8.png)

![image](https://user-images.githubusercontent.com/3049624/64062867-0acace00-cbf5-11e9-8a56-88028078b82b.png)

like time elapsing in the begging but ETA till finish

**Comment by z-------------** [comment]
Hi, thanks for the suggestion. I should be able to implement this very soon.
