### ISSUE TITLE
Click on tray icon doesn't open the interface

### ISSUE THREAD

**Issue by kauron** [z-------------/CPod#171]
**CPod version:** v1.27.1

**Platform:** MacOS 10.15.1

**Install type (.deb, Snap, etc.):** .dmg release

**Description:** if CPod is closed to tray, the only way to reopen it would be left-clicking the tray icon, which in macOS only opens the right-click menu. Therefore the only option is to close the program and reopen it. Similar to #144, but with macOS instead of GNOME.

**Did the bug only appear after a CPod update? Version before, after:** NA

**Steps to reproduce:** open CPod, check the setting "minimize to tray", then close the CPod window. The window cannot be reopened without closing the program.

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:**

**Comment by z-------------** [comment]
Thanks for the issue. I've made it so that the menu always shows the 'Show' item regardless of platform. This will be reflected in the next release.
