### ISSUE TITLE
Can't disable global media keys.

### ISSUE THREAD

**Issue by Uzukii** [z-------------/CPod#172]
**CPod version:**
v1.27.1
**Platform:**
Windows 8.1

Unchecking the box for "Use global media keys" doesn't save on exit. Which is required for the setting to take effect. Therefore it's always enabled and I don't want that. I only just started using CPod so I don't know if this is an issue caused by the last update or not.

**Comment by z-------------** [comment]
Thank you for the bug report. The fix will be present in the next release.
