### ISSUE TITLE
Disable using cache while updating feeds

### ISSUE THREAD

**Issue by EricRKLS** [z-------------/CPod#180]
Hi everyone,

Thanks for making CPod! In version 1.27.1 on Ubuntu it seems like cached results are sometimes used when updating feeds. This results in feeds not being updated while there are new episodes available. After opening the developer tools and disabling the cache, the feeds are always updated correctly. Seems like an easy fix.

Kind regards,
Eric

**Comment by z-------------** [comment]
Hi Eric, dea6682 adds an option to bypass the HTTP cache when updating feeds (by appending a timestamp to request urls).

**Comment by EricRKLS** [comment]
Many thanks! Are there plans for a new version release in the near future? If not, I'll install the latest master.
