### ISSUE TITLE
CPOD closes when clicking on input text "Search or enter URL"

### ISSUE THREAD

**Issue by onoph** [z-------------/CPod#202]
**CPod version:** vCPod v1.27.1

**Platform:**Ubuntu 20

**Installation type (.deb, Snap, etc.):** Ubunrtu Software

**Description:** On search panel => Just click on input text "Search or enter URL". The applications closes

**Version of CPod which introduced the issue (if applicable):** No idea

**Steps to reproduce:**On search panel => Just click on input text "Search or enter URL". The applications closes

**Other information (e.g. Developer Tools console log, screenshots) if possible:**

**Comment by z-------------** [comment]
The issue appears to exist only in the (unofficial) Ubuntu Software Center (Snap) distribution of CPod. See #124, #188.

The problem was resolved in those cases by switching to one of the other distributions found [here](https://github.com/z-------------/CPod/releases).
