### ISSUE TITLE
Icons in welcome screen don't match icons in sidebar

### ISSUE THREAD

**Issue by allisonbickford** [z-------------/CPod#216]
The icons in the sidebar are different from the ones indicated in the onboarding screen, and in a different order.

![image](https://user-images.githubusercontent.com/31906811/96338242-a5d17200-105a-11eb-8aef-d42d978517ab.png)

**Comment by z-------------** [comment]
Thanks. Fixed in 560008057849588d06ffa3be512cf73e4fed8dc0.

I've kept the existing order because it reflects (what I think is) a typical first-use flow.
