### ISSUE TITLE
Progress indicators; better episode filenames

### ISSUE THREAD

**Issue by VJ-Ranga** [z-------------/CPod#69]
**CPod version:**
1.23.5
**Is your feature request related to a problem? Please describe.**
need process bar

**Describe the solution you'd like**
need process bar and download bar. also please set download format mp3 and set offline name on podcast name,episode name

**Comment by z-------------** [comment]
Hi VJ-Ranga, I'm not sure what you mean by "process bar" and "download bar". Are you referring to a list of currently downloading episodes along with their download progress? Please let me know.

Regarding mp3 conversion, I probably won't implement that as it seems a little beyond the scope of this project to me. If more people request it though, I might implement it eventually.

Finally, regarding downloaded filenames, I'll start working soon on the changes you suggest.

Thanks.

**Comment by z-------------** [comment]
An update: commit 8092b495d8c16638c6a675a6e8eebd42da034179 addresses the latter two points (file extension and meaningful naming).

**Comment by VJ-Ranga** [comment]
download bar :- When we are downloading an episode, we can't check whether it is downloading or not 

process bar :- When we are reload home, we can't check whether it is reloading or not. The other thing is when we play episode, we can't see it is loading or not until it starts to play.

downloaded file names :- When we download episode the name comes like "bd7972f8dd2c3bc6236a8f3b3875d87f64c0a51e" this. So can you please create it as "podcast name_episode.mp3" ?
sorry for my bad English....

**Comment by VJ-Ranga** [comment]
i mean we can't track the status of the file,when we are downloading it or reloading the page.Its better to have an progress bar which showing us the status of the process.

**Comment by z-------------** [comment]
Understood. Thanks for the clarification.

**Comment by VJ-Ranga** [comment]
it is so good. but better it have download post and stop button

**Comment by z-------------** [comment]
Glad you like it. I was going to keep this issue open until I added the other things you requested (buffering indicator, download stopping). In any case, I will implement those at some point. Thanks.

**Comment by z-------------** [comment]
@VJ-Ranga, I'm not able to reproduce that problem. Could you try opening the developer tools (Settings, scroll to bottom, "Open developer tools") and send here any errors that show up? Thanks.

**Comment by VJ-Ranga** [comment]
it is not an error. could you change refresh button after refreshing, refresh button(⟳) to close button (x). i think it's fine.

**Comment by z-------------** [comment]
Will do. Thanks.

**Comment by z-------------** [comment]
Updating Home is now disallowed when the device is offline and when a Home update is already in progress.

I've also added download stopping as requested.

These features will be available in a future release of CPod.
