### ISSUE TITLE
Discovery Search should also find results in different languages

### ISSUE THREAD

**Issue by mexpi** [z-------------/CPod#80]
First of all I have to state that CPod is the application I like most when it gets to listen to podcasts. Compliments for your great work! Thank you very much!
The feature I'm still missing most is to use the search to discover new podcasts in German, for example. Maybe it's possible to include German podcast directories in the search?
Thank you!

**Comment by z-------------** [comment]
Hi, are you referring to the Explore section which automatically shows popular podcasts? (The keyword search feature should already be including podcasts from other languages.) I'll work on adding a dropdown to choose what region you want the suggestions to be tailored to. Thanks.

Glad you're enjoying CPod :)

**Comment by z-------------** [comment]
This feature has been completed and will be available in future releases of CPod.
