### ISSUE TITLE
Gpodder Synchronization Fails

### ISSUE THREAD

**Issue by Noammac** [z-------------/CPod#82]
**CPod version:** 1.26.0-pre

**Description of the problem:**
Upon an attempt to synchronize podcast subscriptions with gpodder, an error message arises.

**Steps to reproduce:**
1. Set up a gpodder account
2. Input details into gpodder menu in CPod (email address, password)
3. Generate device ID in the web interface and input into CPod
4. Attempt to subscribe or unsubscribe from a podcast, a red error message will arise saying that CPod could not synchronize with the service. No error message or detail appears in the console.

**Comment by z-------------** [comment]
I'm not able to reproduce this. Just to be sure, are you reloading CPod after inputting your gpodder.net details?

**Comment by z-------------** [comment]
I've just re-read the steps. I believe the problem is that you are inputting the email address associated with your gpodder.net account, rather than your username, which is what the API wants.

**Comment by Noammac** [comment]
Changed to username, seems to have solved the issue.
