### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by KungFung** [z-------------/CPod#83]
1.26.0pre

Okay so firstly I love the design and basically everything of the application but there is one problem that basically stops me form even using it.Basically whenever I click the search or enter url bit CPod just closes.I don't know if this is my systems error or a known bug.

Any help would be appreciated thanks.

**Comment by KungFung** [comment]
I fixed it by just downloading the previous version not the pre release one oops.

**Comment by z-------------** [comment]
Hi there, glad you're enjoying CPod.

Even though you've closed the issue, I'd still like to figure this bug out.

By "previous version", do you mean 1.25.5 or 1.11.0? Are there any special characters etc. in your search terms or URLs?

**Comment by KungFung** [comment]
By previous version I mean 1.25.5 which I downloaded.The issue was with the pre release and the issue consisted of when ever I clicked on the search for podcasts bar it just crashes without me typing anything.

Hopefully this helps.

**Comment by z-------------** [comment]
Yes that helps. Thanks.
