### ISSUE TITLE
Queue Issues

### ISSUE THREAD

**Issue by KungFung** [z-------------/CPod#86]
1.25.5

When I quit CPod my queue just disappears and it becomes **--:--**
![screenshot from 2018-08-19 11-18-41](https://user-images.githubusercontent.com/42492608/44307839-a77f4c80-a3a1-11e8-9ef2-12cb0ffe192e.png)

**Comment by z-------------** [comment]
Can you give me more details, ideally steps to reproduce?

**Comment by KungFung** [comment]
They are recent episodes and they are also subbed podcasts
[-1534770860499.log](https://github.com/z-------------/CPod/files/2302473/-1534770860499.log)

**Comment by KungFung** [comment]
Okay so I can only play one episode and when it goes to the next one it just says an unknown media error occurred

**Comment by KungFung** [comment]
Okay, so I figured it out why some episodes won't play and that is because the episodes haven't fully loaded. But I still haven't figured out why the queue disappears.

**Comment by z-------------** [comment]
The episodes you have trouble with, are they downloaded episodes? If they are, are there characters "#" or "?" in the filename?

**Comment by KungFung** [comment]
Yes they are downloaded episodes and they do have "#" and I'm not sure if this effects it but some also have ":"

**Comment by KungFung** [comment]
Also, I can't play my downloaded episodes offline which I think is related

**Comment by z-------------** [comment]
I believe the downloaded episode problem is the cause behind this issue. I will release 1.25.6 later today which will include a fix.

**Comment by KungFung** [comment]
Okay cool thanks

**Comment by z-------------** [comment]
I've released [v1.25.6](https://github.com/z-------------/CPod/releases/tag/v1.25.6) which should fix this. Please re-open if there are any problems.
