### ISSUE TITLE
not show podcast episode list 

### ISSUE THREAD

**Issue by VJ-Ranga** [z-------------/CPod#88]
**CPod version:**
CPod v1.25.6

i'm using Linux Mint 19 Cinnamon

**Description of the problem:**

not show podcast episode list in home screen
![screenshot from 2018-08-26 17-27-57](https://user-images.githubusercontent.com/32273466/44628008-edb24e00-a955-11e8-9c4e-a03fa97439e9.png)

**Steps to reproduce:**

**Comment by z-------------** [comment]
Please attach a screenshot of the console log (Settings > scroll to bottom > Open developer tools > Console).

**Comment by VJ-Ranga** [comment]
![screenshot from 2018-08-26 17-43-50](https://user-images.githubusercontent.com/32273466/44628113-9f05b380-a957-11e8-9e1f-442ef216c7fa.png)

**Comment by z-------------** [comment]
Sorry about this. Please try [v1.25.7](https://github.com/z-------------/CPod/releases/tag/v1.25.7).

**Comment by z-------------** [comment]
Closed by accident.

**Comment by VJ-Ranga** [comment]
it's work now perfect
