### ISSUE TITLE
file manager crashes app

### ISSUE THREAD

**Issue by Bjelinek26** [z-------------/CPod#93]
when changing download location, the file manager crashes app.  repeated issue when trying to create a new folder.

Ubuntu 18.04.1
GNOME nautilus 3.26.3

from syslog when app crashes:

Sep  5 11:47:59 [92654.315053] cumulonimbus[1133]: segfault at 4 ip 00007f51a63417ed sp 00007fff3b7f68e8 error 4 in libgobject-2.0.so.0.4800.2[7f51a630d000+52000]

**Comment by z-------------** [comment]
These types of issues tend to be due to upstream bugs in Electron. Could you try CPod v1.25.5 (which uses an older Electron version) and let me know if the issue persists? Thanks.

**Comment by Bjelinek26** [comment]
This did seem to fix most of the crashes i was experiencing (downloaded the .deb file and installed with dpkg) .

 However, I now notice that downloaded episodes cannot be played natively in CPod app.  They must be accessed in the ~/.config/cumulonimbus/offline_episodes directory and played with another app.

Second, this version does not appear to have a mechanism to change the download folder or am I missing something?

let me know if you need any logs from me.

thanks

**Comment by z-------------** [comment]
The former is a known bug with 1.25.5 and is fixed in later versions. The latter is a feature introduced in 1.25.6.

I'll soon release a new version of CPod that includes the above but downgrades Electron so the crashes don't occur.

Thanks.

**Comment by z-------------** [comment]
[Here's that new release (1.26.0)](https://github.com/z-------------/CPod/releases/tag/v1.26.0).

**Comment by Bjelinek26** [comment]
thank you, installed from the deb file this morning. So far works very well, can change downloads folder in GUI, can play downloaded episodes in app, like the downloading progress bar

**Comment by z-------------** [comment]
Coolio, I'll close this issue then. Feel free to reopen / open a new one if anything comes up.
